version: "3.7"

services:
  postgres_db:
    image: postgres
    container_name: postgres_db
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rehdera
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=rentx
    volumes:
      - pgdata:/data/postgres
    
    
  app:
    build: .
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    container_name: rentx
    depends_on:
      - postgres_db
    links: 
      - postgres_db
    
       
    
volumes:
  pgdata:
    driver: local




    
    